[profile.default]
src = 'src'
test = 'tests'
script = 'scripts'
out = 'out'
libs = ['lib']
remappings = []
fs_permissions = [{ access = "write", path = "./reports" }]

[rpc_endpoints]
rollux = "${RPC_rolux}"

[etherscan]
rollux = { key = "${ETHERSCAN_API_KEY_ROLLUX}", chainId = 570 }

# See more config options https://github.com/gakonst/foundry/tree/master/config
